artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/AvinashPolisetty/datainfo/raw/main/UCI_Credit_Card.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion 

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/UCI_Credit_Card.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/UCI_Credit_Card.csv

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_training/model.joblib
  metrics_file_path: artifacts/model_evaluation/metrics.json
  test_data_path: artifacts/data_transformation/test.csv

  





